[package]
name = "bevy-settings"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Use a simple struct as persistent settings between game launches. Usefull for e.g. storing the audio settings"
repository = "https://github.com/tecbeast42/bevy-settings"
readme = "README.md"
keywords = ["gamedev", "settings", "persistent"]
categories = ["game-development"]
exclude = [
    ".github/*",
]

[dependencies]
bevy_app = "0.10.0"
bevy_ecs = "0.10.0"
directories = "4.0.1"
serde = "1.0.152"
toml = "0.7.1"

[dev-dependencies]
bevy = "0.10.0"

