[package]
name = "bevy-settings"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.9.1"
bevy_ecs = "0.9.1"
directories = "4.0.1"
serde = "1.0.152"
toml = "0.5.10"

[dev-dependencies]
bevy = "0.9.1"
