name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run : cargo clean
    - name: Try to build
      run: cargo build --verbose
    - name: Try to build all examples
      run: cargo build --examples --verbose
    - name: Run tests
      run: cargo test --verbose
